server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memoria
    username: fabula_app
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: fabula
        format_sql: true
    show-sql: false

internal:
  token: dev-secret-token-provisoire

logging:
  level:
    fr.fae.project.fabula: DEBUG