spring:
  application:
    name: charona

  profiles:
    active:
      - test
      - jpa

  datasource:
    url: jdbc:postgresql://localhost:5432/memoria
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
    default-schema: charona
    liquibase-schema: charona

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: charona
        format_sql: true
    show-sql: false

server:
  port: 8080

jwt:
  secret: clef-H256
  access-token:
    expiration: 86400000
  refresh-token:
    expiration: 604800000
    cookie-secure: false

libria:
  base-url: http://localhost:8083

logging:
  level:
    fr.fae.project.charona: debug