--liquibase formatted sql

--changeset Fae:002-seed-roles
INSERT
INTO charona.roles (code,
                    label,
                    description,
                    assignable,
                    askable)
VALUES ('ROLE_USER',
        'Utilisateur',
        'Accès de base, Charona uniquement.',
        false,
        false),
       ('ROLE_FABULA_USER',
        'Fabula - Utilisateur',
        'Accès à ses propres personnages et notes.',
        true,
        false),
       ('ROLE_FABULA_ADMIN',
        'Fabula — Administrateur',
        'Accès à toutes les données Fabula.',
        true,
        true),
       ('ROLE_HEPHA_USER',
        'Hépha - Utilisateur',
        'Consultation du référentiel SRD.',
        true,
        false),
       ('ROLE_HEPHA_ADMIN',
        'Hépha - Administrateur',
        'Modification et enrichissement du référentiel SRD.',
        true,
        true),
       ('ROLE_LIBRIA_USER',
        'Libria - Utilisateur',
        'Consultation des archives.',
        true,
        false),
       ('ROLE_LIBRIA_ADMIN',
        'Libria - Administrateur',
        'Ajout et indexation de documents.',
        true,
        false),
       ('ROLE_CHARONA_ADMIN',
        'Charona - Administrateur',
        'Gestion des comptes et des rôles',
        true,
        false),
       ('ROLE_MJ',
        'Maître du Jeu',
        'Fonctionnalités MJ transversales sur tous les modules.',
        true,
        true),
       ('ROLE_ADMIN',
        'Administrateur',
        'Accès total, gestion des utilisateurs et des rôles.',
        false,
        false),
       ('ROLE_DEV',
        'Développeur',
        'Accès au Sandbox',
        false,
        false);

